[package]
name = "movable-tiles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0" }
bevy_asset_ron = "0.2.0"
bevy_tilemap = "0.4.0"
rand = "0.8.4"
serde = "1.0.130"
